### ISSUE TITLE
Add ability to bypass dependency check.

### ISSUE THREAD

**Issue by ryanpcmcquen** [ryanpcmcquen/image-ultimator#2]

**Comment by ryanpcmcquen** [comment]
Now possible:
https://github.com/ryanpcmcquen/image-ultimator/commit/5b5ceb94a8aa830fe0e5273772fb86bce1cb15db

@milojennings you may find this useful.

**Comment by milojennings** [comment]
Excellent

**Comment by milojennings** [comment]
How do you use it? Has the documentation been updated?

**Comment by ryanpcmcquen** [comment]
Per the source:

```
## override with DEPENDENCY_CHECKER=off
DEPENDENCY_CHECKER=${DEPENDENCY_CHECKER:-on}
```

I'd rather not put this directly in the documentation, because I want the people who use it to see what is really happening when they override it.

**Comment by ryanpcmcquen** [comment]
So you would run:

```
DEPENDENCY_CHECKER=off imgult
```
