### ISSUE TITLE
Memory usage on a huge count of images

### ISSUE THREAD

**Issue by alpharder** [ryanpcmcquen/image-ultimator#4]
Hello, thanks for the script!

However, when i tried to used in directory containing 14G of images, all 64GB of RAM disappeared :)

Can you please fix it? Looks like all processes start without any wait for previously started processes.

![2016-02-20 1 08 30](https://cloud.githubusercontent.com/assets/1678161/13190533/c139249a-d76e-11e5-9ff9-79496fdf4752.png)

**Comment by ryanpcmcquen** [comment]
What OS are you on? Also what version of `nice` do you have?

**Comment by alpharder** [comment]
Ubuntu Server 14.04.4

abolshakov@ds01:~$ nice --version
nice (GNU coreutils) 8.21

**Comment by ryanpcmcquen** [comment]
What about all the programs `imgult` uses (their versions)?

More specifically, that would be:

```
jpegoptim
mozjpeg <== this is where the 'jpegtran' executable should be coming from
optipng
pngquant
gifsicle
svgo
```

**Comment by ryanpcmcquen** [comment]
Judging by the path you have there, it looks like you are using the system `jpegtran` and not [mozjpeg](https://github.com/mozilla/mozjpeg), this is going to make a huge difference in not only performance, but also the size of images produced ...

**Comment by ryanpcmcquen** [comment]
@alpharder did you ever try installing all the appropriate versions of stuff? It appears another user was able to run `imgult` successfully against **140GB** of images, so your sample should be fine.

Please try the new release as well: https://github.com/ryanpcmcquen/image-ultimator/releases

**Comment by alpharder** [comment]
@ryanpcmcquen We've used another solution that worked well. Thanks!

**Comment by ryanpcmcquen** [comment]
Glad to hear you found something! What did you end up using?

**Comment by alpharder** [comment]
This one: https://github.com/caiguanhao/imgcrush

BTW, there was installed `mozjpeg`, not a `jpegtran`. I've even created symlink for `mozjpeg` binary named as `jpegtran`

**Comment by ryanpcmcquen** [comment]
@alpharder isn't the `mozjpeg` binary called `jpegtran`?

**Comment by alpharder** [comment]
@ryanpcmcquen When I compiled it from source there was `mozjpeg` binary generated.

**Comment by ryanpcmcquen** [comment]
I wonder if the old version Ubuntu ships of `pngquant` was slowing things down (it doesn't even support the `--skip-if-larger` argument).

**Comment by Torkiliuz** [comment]
If you have pngquant `2.0.1 (September 2013)`, which is what gets installed by default in Ubuntu, you're going to have problems optimizing big folders in one run. A combination of updating pngquant to [`2.3.0 (July 2014)`](https://packages.debian.org/jessie/amd64/pngquant/download) and `imgult` to the latest version [`4.0.01`](https://sourceforge.net/projects/image-ultimator/files/4.0.01/HOTFIX%20release..zip/download) will help tremendously :wink:
