### ISSUE TITLE
Default to keep exif data

### ISSUE THREAD

**Issue by klihelp** [ryanpcmcquen/image-ultimator#7]
Can you reconsider, Please keep exif data for default, for location search and copyright support.

**Comment by ryanpcmcquen** [comment]
I'd never heard the copyright argument. You can make it your default by putting something like this in your `~/.bashrc` or `~/.bash_profile`:

```
export EXIFREMOVE=n
```

Let me think about it for a day ...

**Comment by ryanpcmcquen** [comment]
I prefer to remove EXIF data, to protect my own privacy, and I'm guessing there are many people on the same side of that argument, I would suggest you add the option I mentioned above, or just edit this line of the script: https://github.com/ryanpcmcquen/image-ultimator/blob/4.1.01/imgult#L33
